/********************************************************************************
 * Copyright (c) 2015-2018 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 ********************************************************************************/


rootProject.name = 'org.eclipse.mdm'

include 'api:base'
include 'api:odsadapter'
include 'api:atfxadapter'
include 'api:atfxadapter:openatfx'
include 'api:csvadapter'
include 'api:pakadapter'

include 'nucleus'
include 'nucleus:application'
include 'nucleus:connector'
include 'nucleus:apicopy'
include 'nucleus:businessobjects'
include 'nucleus:filerelease'
include 'nucleus:property'
include 'nucleus:freetextindexer'
include 'nucleus:preferences'
include 'nucleus:webclient'
include 'nucleus:importscheduler'

include 'tools:testutils'

include 'doc'
include 'doc:UserGuide'
include 'doc:GettingStartedGuide'
